FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    libvulkan1 vulkan-tools mesa-vulkan-drivers curl ca-certificates && rm -rf /var/lib/apt/lists/*
ARG DOWNLOAD_URL
WORKDIR /app
RUN curl -L ${DOWNLOAD_URL} -o llama.tar.gz && \
    tar -xzvf llama.tar.gz --strip-components=2 && \
    rm llama.tar.gz && \
    chmod +x *
ENTRYPOINT ["./llama-server"]
